export const userRights = {
  AUTHENTICATION_CONTROL: 'Authentication Control', // Expire User
  MASKING_CALLER_ID_LISTING_REPORT: 'Masking/Caller ID Listing Report',
  ADD_ROLE: 'Add Role',
  VIEW_ROLES: 'View Roles',
  ADD_USER: 'Add User',
  VIEW_USERS: 'View Users',
  ADD_GROUP: 'Add Group',
  VIEW_GROUPS: 'View Groups',
  ADD_CONTACT: 'Add Contact',
  VIEW_CONTACTS: 'View Contacts',
  ADD_MESSAGE_TEMPLATE: 'Add Message Template',
  VIEW_MESSAGE_TEMPLATE: 'View Message Template',
  SCHEDULE_SMS_BROADCAST: 'Schedule SMS Broadcast',
  ACCOUNT_INFORMATION: 'Account Information',
  BROADCAST_LOG: 'Broadcast Log',
  INSTANT_SMS: 'Instant SMS',
  UPDATE_MESSAGE_TEMPLATE: 'Update Message Template',
  UPDATE_GROUP: 'Update Group',
  VIEW_GROUP_MEMBERS: 'View Group Members',
  CHANGE_PASSWORD: 'Change Password',
  UPLOAD_LOGO: 'Upload Logo',
  VIEW_SCHEDULED_BROADCASTS: 'View Scheduled Broadcasts',
  EDIT_BROADCAST: 'Edit Broadcast',
  ENABLE_API: 'Enable API',
  DAILY_EMAIL_NOTIFICATION: 'Daily Email Notification',
  BROADCAST_SUMMARY: 'Broadcast Summary',
  ADD_BATCH: 'Add Batch',
  VIEW_BATCH: 'View Batch',
  UPDATE_BATCH: 'Update Batch',
  VIEW_ALL_GROUPS: 'View All Groups',
  BROADCAST_DELIVERED_LOG: 'Broadcast Delivered Log',
  BROADCAST_DELIVERED_LOG_FILES: 'Broadcast Delivered Log Files',
  VIEW_PACKAGE_HISTORY: 'View Package History',
  VIEW_PAYMENT_HISTORY: 'View Payment History',
  ADD_CONTACTS_IN_BULK: 'Add Contacts In Bulk',
  ASSIGN_SMS_GROUP: 'Assign SMS Group',
  ASSIGN_SMS_MASKING: 'Assign SMS Masking',
  ASSIGN_SMS_QUOTA: 'Assign SMS Quota',
  VIEW_SUB_USER_REPORTS: 'View Sub User Reports',
  VIEW_ALL_SCHEDULE_SMS: 'View All Schedule SMS',
  CHANGE_API_PASSWORD: 'Change API Password',
  CHANGE_CONTACT_INFORMATION: 'Change Contact Information',
  DNCR_REPORTING: 'DNCR Reporting',
  VIEW_INVOICE_HISTORY: 'View Invoice History',
  VIEW_PACKAGE_SUBSCRIBE_CUSTOMER: 'View Package Subscribe Customer',
  POSTPAID_BUNDLE_REPORT_CUSTOMER: 'Postpaid Bundle Report Customer',
  VIEW_PACKAGE_HISTORY_MASK_WISE: 'View Package History Mask Wise',
  VOICE_SCHEDULED_BROADCASTS: 'Voice Scheduled Broadcasts',
  VIEW_OBD_GROUPS: 'View OBD Groups',
  VIEW_OBD_GROUP_DETAIL: 'View OBD Group Detail',

  ADD_OBD_GROUP: 'Add OBD Group',
  INSTANT_OBD: 'Instant OBD',
  SCHEDULED_OBD_BROADCAST: 'Scheduled OBD Broadcast',
  OBD_CAMPAIGN_VIEW: 'OBD Campaign View',
  VOICE_SMS: 'Voice SMS',
  DAILY_REPORT: 'Daily Report',
  VIEW_SCHEDULED_OBD_BROADCASTS: 'View Scheduled OBD Broadcasts',
  OBD_VIEW: 'OBD View',
  VIEW_PACKAGE_SUBSCRIBE_OBD_CUSTOMER: 'View Package Subscribe OBD Customer',
  AUTO_ASSIGN_OBD_PACKAGE: 'Auto Assign OBD Package',
  DAILY_OBD_USAGE_REPORT: 'Daily OBD Usage Report',
  CDR_REPORT: 'CDR Report',
  CAMPAIGN_WISE_DAILY_REPORT: 'Campaign Wise Daily Report',
  CAMPAIGN_WISE_MONTHLY_REPORT: 'Campaign Wise Monthly Report',
  ADD_OBD_CONTACT: 'Add OBD Contact',
  VIEW_OBD_CONTACTS: 'View OBD Contacts',
  ADD_OBD_CONTACTS_IN_BULK: 'Add OBD Contacts In Bulk',
  AUTO_ASSIGN_SMS_PACKAGE: 'Auto Assign SMS Package',
  INSTANT_OBD_USER_INPUT: 'Instant OBD User Input',
  MASKING_CALLER_ID_DAILY_REPORT: 'Masking/Caller ID Daily Report',
  PREPAID_PACKAGE_OBD_HISTORY: 'Prepaid Package OBD History',
  SCHEDULED_OBD_BROADCAST_USER_INPUT: 'Scheduled OBD Broadcast User Input',
  POLLS_SURVEY_OBD_REPORT: 'Polls/Survey Obd Report',
  //new
  UPLOAD_AUDIO: 'Upload Audio',
  AUDIO_DETAILS: 'Audio Details',
  INSTANT_AUDIO: 'Instant Audio',
  INSTANT_AUDIO_INPUT: 'Instant Audio Input',
  AUDIO_BROADCAST_SCHEDULE: 'Audio Broadcast Schedule',
  AUDIO_BROADCAST_SCHEDULE_USER_INPUT: 'Audio Broadcast Schedule user Input',
  VIEW_SCHEDULED_AUDIO_BROADCASTS: 'View Scheduled Audio Broadcasts',
  AUDIO_CAMPAIGN_VIEW: 'Audio campaign View',
  VIEW_PACKAGES: 'View Packages',
  USER_CHANGE_PASSWORD: 'User Change Password',
  CHANGE_CONTACT_DETAILS: 'Change Contact Details',
  VIEW_GROUP_DETAIL: 'View Group Detail',
  VIEW_BATCH_DETAIL: 'View Batch Detail',
  SEND_BULK_BATCH: 'Send Bulk Batch',
  CURRENT_BROADCAST_LOGS: 'Current Broadcast Logs',
  ARCHIVED_BROADCAST_LOGS: 'Archived Broadcast Logs',
  POST_PAID_BUNDLE_REPORT: 'Post Paid Bundle Report',
  SUB_USER_CURRENT_BROADCAST_LOGS: 'Sub User Current Broadcast Logs',
  SUB_USER_BROADCAST_SUMMARY: 'Sub User Broadcast Summary',
  SUB_USER_PACKAGE_HISTORY: 'Sub User Package History',
  SUB_USER_ARCHIVED_BROADCAST_LOGS: 'Sub User Archived Broadcast Logs',
  ADD_SCHEDULE_BROADCAST: 'Add Schedule Broadcast',
  VIEW_TEMPLATE: 'View Message Template',
  ADD_TEMPLATE: 'Add Message Template',
  VIEW_AUDIO_FILE: 'View Audio File',
};
